version: '3'

services:
#-------------------------------------

  mysql:
    build:
      context: mysql
    volumes:
      - covid-mysql-db:/var/lib/mysql
      - ./project-data:/usr/src/app/

#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
    networks:
      covid_net:
        ipv4_address: 172.28.1.2

#-------------------------------------

  django:

    build:
      context: django

    volumes:
      - ./project-data:/usr/src/app/

    ports:
      - "8888:8888"


    entrypoint: 
      - /bin/sh
      - /usr/src/app/django/startup.sh

    depends_on:
      - mysql
      
    networks:
      covid_net:
        ipv4_address: 172.28.1.4



networks:
  covid_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  covid-mysql-db: 
    external : yes    
